sudo: false
language: ruby
rvm:
  - 2.3.1
  - ruby-head
  - rbx-3.5.1
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
matrix:
  allow_failures:
    rvm: rbx-3.5.1
script: rspec
