sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.3.0
  - ruby-head
  - rbx-2.5.8
gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
script: rspec
